name: Publish Extension Layer and Invoke Lambda

#  Removed the 'push' trigger to make this workflow manual-only.
on:
  workflow_dispatch:

jobs:
  publish-extension:
    runs-on: ubuntu-latest
    outputs:
      x86_arn: ${{ steps.publish.outputs.x86_arn }}
      arm_arn: ${{ steps.publish.outputs.arm_arn }}
    strategy:
      matrix:
        python-version: [ 3.12 ]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install publish dependencies
        run: pip install -U awscli
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64, amd64
          
      - name: Publish extension layer
        id: publish
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd extension
          ./publish-layer.sh

  invoke-lambda:
    needs: publish-extension 
    runs-on: ubuntu-latest
    steps:
      - name: Invoke for Cold Start
        env:
          API_URL: ${{ secrets.API_GATEWAY_URL }}
          API_KEY: ${{ secrets.API_GATEWAY_KEY }}
        run: |
          echo "Invoking Lambda via API Gateway for cold start..."
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-api-key: $API_KEY" \
            --data '{ "x86_layer_arn": "${{ needs.publish-extension.outputs.x86_arn }}", "arm_layer_arn": "${{ needs.publish-extension.outputs.arm_arn }}", "execution_phase": "cold" }' \
            $API_URL

      - name: Wait for 8 minutes
        run: sleep 480

      - name: Invoke for Warm Start
        env:
          API_URL: ${{ secrets.API_GATEWAY_URL }}
          API_KEY: ${{ secrets.API_GATEWAY_KEY }}
        run: |
          echo "Invoking Lambda via API Gateway for warm start..."
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-api-key: $API_KEY" \
            --data '{ "x86_layer_arn": "${{ needs.publish-extension.outputs.x86_arn }}", "arm_layer_arn": "${{ needs.publish-extension.outputs.arm_arn }}", "execution_phase": "warm" }' \
            $API_URL
